### ISSUE TITLE
Can't refer to external file?

### ISSUE THREAD

**Issue by gjtorikian** [brandur/json_schema#22]
I'd like to be able to split up my jumbo JSON into a smaller file, using references like this:

``` json
"$ref": "file://schemas/json/file.json"
```

It looks like Evaluator's enforcement of `/` as the first char prevents this from happening. Is there any way this can be achieved?

**Comment by vasilakisfil** [comment]
@brandur is there a way to reference a local schema file ?

**Comment by brandur** [comment]
@vasilakisfil Hey! Yes, you should be able to do it using the instructions above. See [my comment here](https://github.com/brandur/json_schema/issues/22#issuecomment-65129746) for information on the general strategy and [@gjtorikian's comment here](https://github.com/brandur/json_schema/issues/22#issuecomment-65238789) for code on using the `DocumentStore` programmatically.
