### ISSUE TITLE
Property name "type".

### ISSUE THREAD

**Issue by panSarin** [brandur/json_schema#47]
In few of our models we have field called 'type'. I want to document it by my json_schema, and use json_schema validator on it. 

But during parsing it i have 
#: {"type"=>"string"} is not a valid "type", must be a array/string.

I get that this edge case is not implemented. Can I make PR with it, or you don't think that is a good idea?

Adam

**Comment by panSarin** [comment]
Srry, i passed bad format of JSON Schema.

**Comment by brandur** [comment]
NP. Glad you got it figured out.
